<Project>

  <Import Project="../version.props" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateFullPaths>True</GenerateFullPaths>
    <OutputPath>../Build/$(Configuration)/$(MSBuildProjectName)</OutputPath>
    <IntermediateOutputPath>../Build/$(Configuration)/$(MSBuildProjectName)/obj</IntermediateOutputPath>
    <PackageOutputPath>../Build/$(Configuration)</PackageOutputPath>
    <NoWarn>436</NoWarn>
    <Authors>Topten Software</Authors>
    <Company>Topten Software</Company>
    <TtsCodeSign>False</TtsCodeSign>
    <DocumentationFile>$(OutputPath)/$(AssemblyName).xml</DocumentationFile>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../version.cs" Link="version.cs" />
  </ItemGroup>

  <Target Name="Code Sign" AfterTargets="Build" Condition="$(TtsCodeSign) And '$(TargetFileName)'!=''">
    <Exec Command="ttssign $(TargetDir)$(TargetFileName)" />
  </Target>

  <Target Name="InheritDoc" AfterTargets="PostBuildEvent" Condition="$(GenerateDocumentationFile) And $(TtsInheritDoc)">
    <PropertyGroup>
      <_InheritDocPath>$([MSBuild]::NormalizePath($(OutputPath)).TrimEnd('\'))</_InheritDocPath>
    </PropertyGroup>
    <Exec Command="dotnet &quot;%USERPROFILE%\.dotnet\tools\.store\inheritdoctool\2.5.2\inheritdoctool\2.5.2\tools\netcoreapp3.1\any\InheritDoc.dll&quot; -b &quot;$(_InheritDocPath)&quot; -f $(AssemblyName).xml --overwrite" />
  </Target>

  <ItemGroup>
      <None Include="../buildtools/nuget-icon.png" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**" />
  </ItemGroup>

</Project>